# Generated by Django 4.2.16 on 2024-11-18 17:29

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvolume",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="product_volume_image",
            ),
        ),
    ]
