# Generated by Django 4.2.16 on 2024-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productvolume_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Description"
            ),
        ),
    ]
