# Generated by Django 4.2.16 on 2024-11-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("MTN", "MTN Payment"),
                    ("Visa", "Visa Payment"),
                    ("MasterCard", "MasterCard Payment"),
                    ("PayPal", "PayPal Payment"),
                ],
                default="Cash",
                max_length=20,
            ),
        ),
    ]
