# Generated by Django 4.2.16 on 2024-11-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payer_phone_number",
        ),
    ]
