# Generated by Django 4.2.16 on 2024-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_payer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("MTN MOMO", "MTN Mobile Money")],
                default="MTN MOMO",
                max_length=20,
            ),
        ),
    ]
