# Generated by Django 4.2.16 on 2024-11-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Mobile Money", "Mobile Money")],
                default="MTN MOMO",
                max_length=20,
            ),
        ),
    ]
