# Generated by Django 4.2.16 on 2024-12-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_saledetail_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saledetail",
            name="volume",
        ),
    ]
