# Generated by Django 4.2.16 on 2024-12-08 19:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_remove_saledetail_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saledetail",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="saledetail",
            name="total_detail",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
