# Generated by Django 4.2.16 on 2024-12-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_saledetail_price_alter_saledetail_total_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saledetail",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="saledetail",
            name="total_detail",
            field=models.FloatField(),
        ),
    ]
