# Generated by Django 4.2.16 on 2024-12-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_description"),
        ("sales", "0005_alter_saledetail_price_alter_saledetail_total_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="saledetail",
            name="product_volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productvolume",
            ),
        ),
    ]
