services:
  - type: web
    name: jobel_retail
    env: python
    plan: free  # or `starter` or other depending on your Render plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: |
      python manage.py migrate && gunicorn core.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-%og791$c!c7zkz*xe7^4a40s4k-g0dtw_4_u#e6yd3znt@f$w&
      - key: DATABASE_URL
        value: postgresql://jobel_db_user:pO3I0rkmYq1k9qQGA8oyzKlOSPubvaR6@dpg-cshuhk1u0jms73f6pm80-a/jobel_db
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: jobel_retail.onrender.com,localhost
