# Generated by Django 4.2.16 on 2024-11-29 19:50

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="youtube_url",
        ),
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="url_content",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[apps.blog.models.validate_youtube_url],
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
