# Generated by Django 4.2.16 on 2024-11-18 17:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                default="default.jpg", max_length=255, verbose_name="avatar"
            ),
        ),
    ]
